module.exports=[
    {
        path:'/home',
        label:'首页',
        name:'home',
        icon:'user-solid'
    },
    {
        path:'/video',
        label:'视频管理',
        name:'video',
        icon:'video-play'
    },
    {
        path:'/user',
        label:'用户管理',
        name:'user',
        icon:'user'
    },
    {
        label:'其他',
        icon:'map-location',
        children:[
            {
                path:'/page1',
                name:'page1',
                label:'页面1'
            },
            {
                path:'/page2',
                name:'page2',
                label:'页面2'
            },
            {
                path:'/page3',
                name:'page3',
                label:'页面3'
            }
        ]
    }
]